### ISSUE TITLE
Missing pfx file

### ISSUE THREAD

**Issue by barankaynak** [DesignEngrLab/MIConvexHull#19]
MIConvexHull.pfx file is missing. Project can't be building.

**Comment by datafile4** [comment]
I have the same issue with building.

**Comment by takarzyna** [comment]
You can sign the project yourself through Properties/Signing:
https://stackoverflow.com/questions/35475059/how-to-generate-a-new-pfx-file-after-being-lost-from-source-control

**Comment by micampbell** [comment]
thanks for pointing this out. I think it is fixed now.

**Comment by synnestenvold** [comment]
I still have this problem. Could not find the DesignEngineeringLab.pfx file.
