### ISSUE TITLE
Delaunay triangulation edge case ?

### ISSUE THREAD

**Issue by rienafairefr** [DesignEngrLab/MIConvexHull#7]
I'm trying to use MIConvexHull to generate a triangulation for scattered 2D data for heightmap, and I've apparently reduced the problem to this minimal cases: 

    [Test]
    public void TestMi1()
    {
    	var vertices = new List<Vertex>
    	{
    		new Vertex(1, 0.5),
    		new Vertex(0, 1),
    		new Vertex(0, 0),
    		new Vertex(1, 0)
    	};
    	DelaunayTriangulation<Vertex, Cell>.Create(vertices);
    }
    [Test]
    public void TestMi2()
    {
    
    	var vertices2 = new List<Vertex>
    	{
    		new Vertex(1, 1),
    		new Vertex(0, 1),
    		new Vertex(0, 0),
    		new Vertex(1, 0)
    	};
    	DelaunayTriangulation<Vertex, Cell>.Create(vertices2);
    }

TestMi1 passes, but TestMi2 fails with

    The input data is degenerate. It appears to exist in 3 dimensions, 
    but it is a 2 dimensional set (i.e. the point of collinear, coplanar, or co-hyperplanar.)

What's going on here ?

**Comment by micampbell** [comment]
I'm sorry to take so long to respond to this. I am working on a solution. This is something my co-author tried to convince me of long ago, but I'm now just understand the issue.

**Comment by roy-t** [comment]
By chance any ETA on this problem? I've got into this problem with a similar test case:

```
var rectangle = new List<Vertex>
{
    new Vertex(0, 0),
    new Vertex(1, 0),
    new Vertex(0, 1),
    new Vertex(1, 1),
};
DelaunayTriangulation<Vertex, Cell>.Create(vertices);
```

This is pretty troublesome for me since I would like to start with a rectangle, triangulate this and then slowly add more points :). Your package looks perfect for this, except for this little bug. 

A quick fix for me, for now is to add a fifth point (anywhere).

**Comment by micampbell** [comment]
I believe I have fixed this now. Please use the latest and let me know if it works.

**Comment by roy-t** [comment]
@micampbell @rienafairefr 

I've installed NuGet Package 1.1.17.409.

The following test case now works:

```
new Vertex(1, 1),
new Vertex(0, 1),
new Vertex(0, 0),
new Vertex(1, 0)	
```

However, this test case still fails:
```
new Vertex(-1,-1),
new Vertex(1, -1),
new Vertex(1,1),
new Vertex(-1, 1)	
```

Adding a fifth point at (0,0). Or changing one of the points to be not exactly at -1 or 1 fixes it.

(Is there a re-open button somewhere? I can't seem to find it).

**Comment by micampbell** [comment]
Ah! you are good at finding the edge-cases. Again, I was too stubborn to see these problems when my co-author brought them up years ago. Anyway, that is fixed now too. Let me know if you have others. Were you also interested in an Update function as well? One that would take an existing convex hull are one or more new points?

**Comment by roy-t** [comment]
Awesome, everything works perfectly on my end now :).

Actually being able to update a DelaunayTriangulation by adding, removing, or moving, a vertex would be cool. But at this moment the algorithm is so fast that I have no problems with just recalculating the whole thing.

(Actually I made a mistake in my code so that DelaunayTriangulation.Create was called each frame instead of only when something in the vertices changed, and I didn't notice for weeks :)).

**Comment by dannypike** [comment]
Hopefully, I have misunderstand something, because I've only just started playing with this library, but hard-wiring the "lift" parameter in this call to true:

```
var ch = new ConvexHullAlgorithm(data.Cast<IVertex>().ToArray(), true, PlaneDistanceTolerance);
```

seems to be causing me to hit an exception, when I pass in a simple 3D "bent" square as a test:

```
new Vertex { Position = new [] { 0.0, 0.0, 0.0 } },
new Vertex { Position = new [] { 1.0, 0.0, 1.0 } },
new Vertex { Position = new [] { 1.0, 1.0, 0.0 } },
new Vertex { Position = new [] { 0.0, 1.0, 1.0 } },
```

The exception is:

> There are too few vertices (m) for the n-dimensional space. (m must be greater 
> than the n, but m is " + NumberOfVertices + " and n is " + NumOfDimensions);

On single-stepping through the implementation, the call to `DetermineDimension()` correctly determines that the input data has three dimensions. The code then unconditionally increments this by one (because `lift` is hard-coded to `true`), and throws an exception because, unsurprisingly, it notices that n + 1 is not equal to n.

Am I doing something wrong?

**Comment by dannypike** [comment]
Please ignore the question, I need more sleep
